routes/web.php
<?php

use App\Events\MessagePosted;
use App\Message;
use Illuminate\Support\Facades\Auth;

Route::group(
[
	'prefix' => LaravelLocalization::setLocale(),
	'middleware' => [ 'localize', 'localizationRedirect', 'activity' ]
],
function()
{
    Route::get('/', 'HomeController@index');
    Route::get('contractProve/{id}', ['as'=> 'contractProve', 'uses' => 'HomeController@contractProve']);
    Route::get('categories', 'HomeController@categoryPage');
    Route::get('profile', 'HomeController@profile');
	Route::get('profileEdit', 'HomeController@profileEdit');
    Route::get('api/getCities','HomeController@getCities');
    Route::get('api/getDistricts','HomeController@getDistricts');
    Route::post('registeration', 'HomeController@registeration');
    Auth::routes(['verify' => true]);

    Route::get('products', 'ProductFrontController@index');
    Route::get('product/{slug}', ['as'=> 'product.show', 'uses' => 'ProductFrontController@show']);
    Route::get('category/{id}', 'ProductFrontController@showByCategory');
    Route::post('price-request', 'ProductFrontController@priceRequest');
    Route::post('price-offer', 'ProductFrontController@priceOffer');

    Route::get('dashboard', 'Dashboard\DashboardController@index');
    Route::get('reserves', 'Dashboard\DashboardController@reserves');
    Route::get('contracts', 'Dashboard\ContractController@index');
    Route::get('contract/{id}', 'Dashboard\ContractController@view');
    Route::post('contractLoad', 'Dashboard\ContractController@contractLoad');
    Route::get('contractApprove/{id}', 'Dashboard\ContractController@approve');
    Route::get('notification/{id}', 'Dashboard\DashboardController@notification');
    Route::resource('ownProducts','Dashboard\ProductController');
    Route::get('productRefresh/{id}', 'Dashboard\ProductController@refresh');
    Route::resource('rkps', 'Dashboard\RkpController');

    Route::get('api/getChildCategories','Dashboard\ProductController@getChildCategories');
    Route::get('api/getUserSaldo','Dashboard\ProductController@getUserSaldo');
});

Route::group(['prefix' => 'backend','middleware' => ['role:admin', 'activity']], function() {

	Route::get('/', 'Admin\Backend');

    Route::resource('roles','Admin\RoleController');
    Route::resource('users','Admin\UserController');
    Route::resource('permissions','Admin\PermissionController');

    Route::resource('rkpsAdmin', 'Admin\RkpBackendController');
    Route::resource('payments', 'Admin\PaymentController');

    Route::resource('cities', 'Admin\CityController');
    Route::resource('districts', 'Admin\DistrictController');

    Route::resource('categories', 'Admin\CategoryController');
    Route::resource('childCategories', 'Admin\CategoryChildController');

    Route::resource('measures', 'Admin\MeasureController');
    Route::resource('currencies', 'Admin\CurrencyController');
    Route::resource('basises', 'Admin\BasisController');
    Route::resource('products', 'Admin\ProductController');

    Route::get('contracts', ['as' => 'contracts.index', 'uses' => 'Admin\ContractsController@index']);
    Route::get('contractStatuses', ['as' => 'contractStatuses.index', 'uses' => 'Admin\ContractStatusesController@index']);
    Route::post('docPayments', ['as' => 'docPayment.create','uses' => 'Admin\PaymentController@docPaymentCreate']);

    Route::resource('holidays', 'Admin\HolidaysController');
    Route::resource('statuses', 'Admin\StatusController');
    Route::get('params', ['as' => 'params.index', 'uses' => 'Admin\SystemParamsController@index']);
    Route::put('params', ['as' => 'params.update', 'uses' => 'Admin\SystemParamsController@update']);

    Route::get('api/getDistricts','Admin\UserController@getDistricts');
    Route::get('users/reset/{id}','Admin\UserController@reset');

});
Route::group(['prefix' => 'messages', 'middleware'=> ['activity']], function () {
    Route::get('/', ['as' => 'messages', 'uses' => 'Dashboard\MessagesController@index']);
    Route::get('/sent', ['as' => 'messages.sent', 'uses' => 'Dashboard\MessagesController@sent']);
    Route::get('create', ['as' => 'messages.create', 'uses' => 'Dashboard\MessagesController@create']);
    Route::post('/', ['as' => 'messages.store', 'uses' => 'Dashboard\MessagesController@store']);
    Route::get('{id}', ['as' => 'messages.show', 'uses' => 'Dashboard\MessagesController@show']);
    Route::put('{id}', ['as' => 'messages.update', 'uses' => 'Dashboard\MessagesController@update']);

});

app/Models/District.php
<?php

namespace App\Models;

use App\User;
use Eloquent as Model;


class District extends Model
{
    use \Dimsav\Translatable\Translatable;

    public $table = 'district';

    protected $dates = ['deleted_at'];

    public $translatedAttributes = [
        'title',
    ];

    public $fillable = [
        'user_id',
        'district_city_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'user_id' => 'integer',
        'district_city_id' => 'integer'
        //'featured_image' => 'string'
    ];

    public static $rules = [
        'district_city_id' => 'integer|required',
        'ru.title' => 'required|string|min:3|max:255',
        'uz.title' => 'required|string|min:3|max:255',
        'en.title' => 'required|string|min:3|max:255'
    ];

    protected static function boot() {
        parent::boot();

        static::deleting(function($news) {
            $news->deleteTranslations();
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function city()
    {
        return $this->belongsTo(City::class, 'district_city_id', 'id');
    }
}

app/Http/Controllers/Admin/DistrictController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\DistrictRequest;
use App\Models\District;
use App\Models\City;
use App\Repositories\DistrictRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;
use App;

class DistrictController extends AppBaseController
{

    private $districtRepository;

    public function __construct(DistrictRepository $districtRepo){
        $this->districtRepository = $districtRepo;
        $this->defaultLocale = 'ru';
        App::setLocale($this->defaultLocale);
    }

    public function index(Request $request)
    {
        $this->districtRepository->pushCriteria(new RequestCriteria($request));
        $districts = $this->districtRepository->paginate(20);
        return view('admin.district.index')->with('districts', $districts);
    }

    public function create()
    {
        $cities = City::withTranslation()->get();

        $citiesArray = [];

        foreach($cities as $city) {
            $citiesArray[$city->id] = $city->title;
        }

        return view('admin.district.create', compact(['citiesArray']));
    }

    public function store(DistrictRequest $request)
    {
        $district = new District();

        $district->fill($request->except(['_token']));

        $district->save();

        Flash::success('Город успешно сохранен.');

        return redirect(route('districts.index'));
    }

    public function show(){}

    public function edit($id)
    {
        $district = $this->districtRepository->findWithoutFail($id);

        $cities = City::withTranslation()->get();

        $citiesArray = [];

        foreach($cities as $city) {
            $citiesArray[$city->id] = $city->title;
        }

        if (empty($district)) {
            Flash::error('Город не найден');
            return redirect(route('districts.index'));
        }

        return view('admin.district.edit', compact(['district','citiesArray']));
    }

    public function update($id, DistrictRequest $request)
    {
        $district = $this->districtRepository->findWithoutFail($id);

        if (empty($district)) {
            Flash::error('Город не найден');
            return redirect(route('districts.index'));
        }

        $district->fill($request->except(['_token']));

        $district->save();

        Flash::success('Город успешно обновлен.');

        return redirect(route('districts.index'));
    }

    public function destroy($id)
    {
        $this->districtRepository->delete($id);

        Flash::success('Город успешно удален.');

        return redirect(route('districts.index'));
    }
}

resources/views/admin/district/create.blade.php
<?php ?>
@extends('admin.layouts.app')

@section('content')
    <div class="">
        <div class="row">
                <div class="panel panel-default">
                    <div class="panel-heading">Create New District</div>

                    <div class="panel-body">
                        <!-- Display Validation Errors -->
                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        {!! Form::open(['route' => 'districts.store']) !!}

                            @include('admin.district.fields')

                        {!! Form::close() !!}

                    </div>
                </div>
            </div>
        </div>
@endsection

resources/views/admin/district/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Edit district
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($district, ['route' => ['districts.update', $district->id], 'method' => 'patch']) !!}

                        @include('admin.district.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/admin/district/fields.blade.php
<div class="nav-tabs-custom col-xs-12">
    <ul class="nav nav-tabs">
        <?php 
        $key = 1;
        foreach( LaravelLocalization::getSupportedLocales() as $locale => $properties ): ?>

        <li class="{{ $key==1 ? 'active' : '' }}">
            <a href="#tab_{{ $key }}" data-toggle="tab">
                <span class="locale-title"><i class="fa fa-globe" aria-hidden="true"></i> {{ $properties['native'] }}</span>
            </a>
        </li>

        <?php $key++; endforeach; ?>
    </ul>

    <div class="tab-content">
        <?php $key = 1;
        foreach( LaravelLocalization::getSupportedLocales() as $locale => $properties ): ?>
        <div class="tab-pane {{ $key==1 ? 'active' : '' }}" id="tab_{{ $key }}">

            <div class="form-group col-sm-6">
                {!! Form::label($locale.'[title]', 'Заголовок:') !!}
                {{ Form::text(
                    $locale.'[title]',
                    isset($district) ? $district->translate($locale)->title : null,
                    ['class' => 'form-control'])
                }}
            </div>
        </div>
        <?php $key++; endforeach; ?>
    </div>
    <!-- /.tab-content -->



<div class="form-group col-sm-12">
    {!! Form::label('district_city_id', 'City') !!}
    {!! Form::select('district_city_id', $citiesArray, null, ['class' => 'form-control']) !!}
</div>

<div class="clearfix"></div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('districts.index') !!}" class="btn btn-default">Cancel</a>
</div>

</div>

resources/views/admin/district/index.blade.php
<?php ?>
@extends('admin.layouts.app')

@section('content')
    <div class="container">
        <div class="row">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Города
                        <a href="{{ route('districts.create') }}" class="btn btn-success">
                            <i class="fa fa-btn fa-plus"></i> 
                            &nbsp;Новый город
                        </a>
                    </div>
                    <div class="panel-body">
                        @include('flash::message')
                        <table class="table table-striped table-bordered table-condensed">
                            <thead>
                            <tr>
                                <th>Название</th>
                                <th>Название региона</th>
                                <th>Действия</th>
                            </tr>
                            </thead>
                            <tbody>

                            @foreach ($districts as $key => $district)

                                <tr class="districts-users">
                                    <td>{{ $district->translate('ru')->title }}</td>
                                    <td>{{ $district->city->translate('ru')->title }}</td>
                                    <td>
                                        <a class="btn btn-primary" href="{{ route('districts.edit',$district->id) }}"><i class="fa fa-btn fa-edit"></i> Edit</a>

                                        <form action="{{ url('backend/districts/'.$district->id) }}" method="POST" style="display: inline-block">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}

                                            <button type="submit" id="delete-task-{{ $district->id }}" class="btn btn-danger">
                                                <i class="fa fa-btn fa-trash"></i> Delete
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                {{ $districts->links() }}
            </div>
        </div>
@endsection