routes/web.php
<?php

use App\Events\MessagePosted;
use App\Message;
use Illuminate\Support\Facades\Auth;

Route::group(
[
	'prefix' => LaravelLocalization::setLocale(),
	'middleware' => [ 'localize', 'localizationRedirect', 'activity' ]
],
function()
{
    Route::get('/', 'HomeController@index');
    Route::get('contractProve/{id}', ['as'=> 'contractProve', 'uses' => 'HomeController@contractProve']);
    Route::get('categories', 'HomeController@categoryPage');
    Route::get('profile', 'HomeController@profile');
	Route::get('profileEdit', 'HomeController@profileEdit');
    Route::get('api/getCities','HomeController@getCities');
    Route::get('api/getDistricts','HomeController@getDistricts');
    Route::post('registeration', 'HomeController@registeration');
    Auth::routes(['verify' => true]);

    Route::get('products', 'ProductFrontController@index');
    Route::get('product/{slug}', ['as'=> 'product.show', 'uses' => 'ProductFrontController@show']);
    Route::get('category/{id}', 'ProductFrontController@showByCategory');
    Route::post('price-request', 'ProductFrontController@priceRequest');
    Route::post('price-offer', 'ProductFrontController@priceOffer');

    Route::get('dashboard', 'Dashboard\DashboardController@index');
    Route::get('reserves', 'Dashboard\DashboardController@reserves');
    Route::get('contracts', 'Dashboard\ContractController@index');
    Route::get('contract/{id}', 'Dashboard\ContractController@view');
    Route::post('contractLoad', 'Dashboard\ContractController@contractLoad');
    Route::get('contractApprove/{id}', 'Dashboard\ContractController@approve');
    Route::get('notification/{id}', 'Dashboard\DashboardController@notification');
    Route::resource('ownProducts','Dashboard\ProductController');
    Route::get('productRefresh/{id}', 'Dashboard\ProductController@refresh');
    Route::resource('rkps', 'Dashboard\RkpController');

    Route::get('api/getChildCategories','Dashboard\ProductController@getChildCategories');
    Route::get('api/getUserSaldo','Dashboard\ProductController@getUserSaldo');
});

Route::group(['prefix' => 'backend','middleware' => ['role:admin', 'activity']], function() {

	Route::get('/', 'Admin\Backend');

    Route::resource('roles','Admin\RoleController');
    Route::resource('users','Admin\UserController');
    Route::resource('permissions','Admin\PermissionController');

    Route::resource('rkpsAdmin', 'Admin\RkpBackendController');
    Route::resource('payments', 'Admin\PaymentController');

    Route::resource('cities', 'Admin\CityController');
    Route::resource('districts', 'Admin\DistrictController');

    Route::resource('categories', 'Admin\CategoryController');
    Route::resource('childCategories', 'Admin\CategoryChildController');

    Route::resource('measures', 'Admin\MeasureController');
    Route::resource('currencies', 'Admin\CurrencyController');
    Route::resource('basises', 'Admin\BasisController');
    Route::resource('products', 'Admin\ProductController');

    Route::get('contracts', ['as' => 'contracts.index', 'uses' => 'Admin\ContractsController@index']);
    Route::get('contractStatuses', ['as' => 'contractStatuses.index', 'uses' => 'Admin\ContractStatusesController@index']);
    Route::post('docPayments', ['as' => 'docPayment.create','uses' => 'Admin\PaymentController@docPaymentCreate']);

    Route::resource('holidays', 'Admin\HolidaysController');
    Route::resource('statuses', 'Admin\StatusController');
    Route::get('params', ['as' => 'params.index', 'uses' => 'Admin\SystemParamsController@index']);
    Route::put('params', ['as' => 'params.update', 'uses' => 'Admin\SystemParamsController@update']);

    Route::get('api/getDistricts','Admin\UserController@getDistricts');
    Route::get('users/reset/{id}','Admin\UserController@reset');

});
Route::group(['prefix' => 'messages', 'middleware'=> ['activity']], function () {
    Route::get('/', ['as' => 'messages', 'uses' => 'Dashboard\MessagesController@index']);
    Route::get('/sent', ['as' => 'messages.sent', 'uses' => 'Dashboard\MessagesController@sent']);
    Route::get('create', ['as' => 'messages.create', 'uses' => 'Dashboard\MessagesController@create']);
    Route::post('/', ['as' => 'messages.store', 'uses' => 'Dashboard\MessagesController@store']);
    Route::get('{id}', ['as' => 'messages.show', 'uses' => 'Dashboard\MessagesController@show']);
    Route::put('{id}', ['as' => 'messages.update', 'uses' => 'Dashboard\MessagesController@update']);

});

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use Mcamara\LaravelLocalization\Facades\LaravelLocalization;
use App\Http\Controllers\AppBaseController;
use Intervention\Image\Facades\Image;
use Illuminate\Http\UploadedFile;
use App\Models\Status;
use App\Models\ChildCategory;
use Illuminate\Http\Request;
use App\Models\Holidays;
use App\Models\Category;
use App\Models\Currency;
use App\Models\Product;
use App\Models\Country;
use App\Models\Measure;
use App\Models\Basis;
use Carbon\Carbon;
use App\User;
use Flash;
use DB;

class ProductController extends AppBaseController
{
    public function index(Request $request)
    {
        $products = Product::whereTranslation('locale', 'ru')->
                    orderBy('status', 'asc');


        if ($request->has('name') && $request->name !== null) {
            $products->whereTranslationLike('title', '%'.$request->name.'%');
        }

        if ($request->has('status') && $request->status !== null) {
            $products->where('status', $request->status);
        }
        if ($request->has('main_category') && $request->main_category !== null) {
            $products->where('parent_category_id', $request->main_category);
        }
        if ($request->has('child_category') && $request->child_category !== null) {
            $products->where('child_category_id', $request->child_category);
        }

        $statuses = Status::whereTranslation('locale', 'ru')->get();
        $statusesArray = [];
        foreach($statuses as $item) {$statusesArray[$item->id] = $item->name;}

        $categories = Category::whereTranslation('locale', 'ru')->get();
        $categoriesArray = [];
        foreach($categories as $item) {$categoriesArray[$item->id] = $item->title;}

        $categoriesChild = ChildCategory::whereTranslation('locale', 'ru')->
        where('category_id', $request->main_category)->
        get();
        $categoriesChildArray = [];
        foreach($categoriesChild as $item) {$categoriesChildArray[$item->id] = $item->title;}



        $products = $products->
        paginate(15)->appends($request->all());


        return view('admin.products.index',compact(['products', 'categoriesArray', 'categoriesChildArray', 'statusesArray', 'request']));
    }

    public function edit($id)
    {
        $product = Product::where('id', $id)->first();

        if (empty($product)) {
            return redirect(route('products.index'))->with('data', 'Product not found');
        }

        $categories = Category::whereTranslation('locale', 'ru')->get();
        $categoriesArray = [];
        foreach($categories as $item) {$categoriesArray[$item->id] = $item->title;}

        $categoriesChild = ChildCategory::whereTranslation('locale', 'ru')->
                                            where('category_id', $product->parent_category_id)->
                                            get();
        $categoriesChildArray = [];
        foreach($categoriesChild as $item) {$categoriesChildArray[$item->id] = $item->title;}

        $measures = Measure::whereTranslation('locale', 'ru')->get();
        $measuresArray = [];
        foreach($measures as $item) {$measuresArray[$item->id] = $item->title;}

        $currency = Currency::get();
        $currencyArray = [];
        foreach($currency as $item) {$currencyArray[$item->id] = $item->code;}

        $basis = Basis::get();
        $basisArray = [];
        foreach($basis as $item) {$basisArray[$item->id] = $item->code;}

        $country = Country::whereTranslation('locale', 'ru')->get();
        $countryArray = [];
        foreach($country as $item) {$countryArray[$item->id] = $item->title;}

        $statuses = Status::whereTranslation('locale', 'ru')->get();
        $statusesArray = [];
        foreach($statuses as $item) {$statusesArray[$item->id] = $item->name;}

        if ($product->status == Status::NO_PAID_COMMISSION) {
            $message = parent::reserveMoney($product, $product->user_id);
            if($message)
                Flash::error($message);
            else{
                $product->status = Status::IN_MODERATION_NEW;
                $product->save();
                Flash::success('Комисионный сбор и Депозить успешно снято');
            }
        }

        return view('admin.products.edit', compact(['product','categoriesArray', 'measuresArray', 'currencyArray', 'basisArray', 'countryArray', 'statusesArray', 'categoriesChildArray']));
    }

    public function update($id, Request $request)
    {
        $this->validate($request, Product::$rules);

        $product = Product::where('id', $id)->first();

        if (empty($product)) {
            Flash::error('Product not found');
            return redirect(route('products.index'));
        }

        if ($product->status == Status::IN_MODERATION_NEW && $request['status'] == Status::ACTIVE) {
            $product->updated_at = Carbon::now();
            $holidays = Holidays::where('holiday', '>', Carbon::now())->get();
            $holidays = $holidays->toArray();

            $MyDateCarbon = Carbon::now();
            $MyDateCarbon->addWeekdays(10);

            for ($i = 1; $i <= 10; $i++) {

                if (in_array(Carbon::now()->addWeekdays($i)->toDateString(), $holidays)) {

                    $MyDateCarbon->addDay();

                }
            }

            $request->merge(['expire_at' => $MyDateCarbon]);
        }

        $product->fill($request->except(['featured_image']));

        if ($request->hasFile('featured_image')) {
            $this->removePhoto( $product->featured_image );
            $product->featured_image = $this->uploadPhoto( $request->file('featured_image') );
        }

        $product->save();

        Flash::success('Product updated successfully.');
        return redirect(route('products.index'));
    }


    public function destroy($id)
    {
        $product = Product::where('id', $id)->first();

        if (empty($product)) {
            Flash::error('Product not found');
            return redirect(route('products.index'));
        }

        $product->status = Status::BLOCKED;
        $product->save();

        Flash::success('Product frozen successfully.');

        return redirect(route('products.index'));
    }

    protected function uploadPhoto(UploadedFile $file) {

        $base_name = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
        $image_name = str_slug($base_name, '_').'_'.time().'.'.$file->getClientOriginalExtension();

        $file->move(public_path('uploads/product/'), $image_name);

        Image::make(public_path('uploads/product/').$image_name)
            ->fit(100)
            ->save(public_path('uploads/product/').'admin_'.$image_name);

        Image::make(public_path('uploads/product/').$image_name)
            ->fit(720, 960)
            ->save(public_path('uploads/product/').'thumb_'.$image_name);

        Image::make(public_path('uploads/product/').$image_name)
            ->fit(1200, 1600)
            ->save(public_path('uploads/product/').'icon_'.$image_name);

        return $image_name;
    }

    protected function removePhoto( $image_name ) {

        if( !empty($image_name) ) {
            unlink( public_path('uploads/product/').$image_name );
            unlink( public_path('uploads/product/admin_').$image_name );
            unlink( public_path('uploads/product/thumb_').$image_name );
            unlink( public_path('uploads/product/icon_').$image_name );
        }
    }
}

app/Http/Controllers/Dashboard/ChatsController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ChatsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        return view('dashboard.chats.chats');
    }
}

app/Http/Controllers/Dashboard/ContractController.php
<?php
namespace App\Http\Controllers\Dashboard;

use QrCode;
use App\Models\Contract;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\URL;
use App\Http\Controllers\AppBaseController;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

class ContractController extends AppBaseController
{
    private $locale;

    public function __construct()
    {
        $this->middleware('auth');
        $this->locale = LaravelLocalization::getCurrentLocale();
    }

    public function index(Request $request)
    {
        $contracts = Contract::orWhere('s_client_id', auth()->id())->orWhere('b_client_id', auth()->id())->orderBy('created_at', 'desc')->paginate(15);
        return view('dashboard.contracts.index', compact(['contracts']));
    }

    public function view($id)
    {
        $contract = Contract::where('id', $id)->first();
        return view('dashboard.contracts.show', compact(['contract']));
    }

    public function contractLoad(Request $request)
    {
        $file = resource_path() . '\contracts\ready\_' . $request->doc . '.docx';

        $headers = [
            'Content-Type' => 'application/docx',
        ];

        return response()->download($file, $request->doc . '.docx', $headers);
    }

    public function approve($id)
    {
        $contract = Contract::where('id', $id)->first();

        if (empty($contract)) {
            return redirect(url('contracts'))->with('data', 'Контракт не найден.');
        }

        switch (auth()->id()) {
            case $contract->s_client_id:
                switch ($contract->status) {
                    case 1:
                        $contract->status = 2;
                        break;
                    case 2:
                        return redirect(url('contracts'))->with('data', 'Вы уже одобрили.');
                        break;
                    case 3:
                        $contract->status = 4;
                        $this->contractDocPopulate($contract);
                }
                break;
            case $contract->b_client_id:
                switch ($contract->status) {
                    case 1:
                        $contract->status = 3;
                        break;
                    case 3:
                        return redirect(url('contracts'))->with('data', 'Вы уже одобрили.');
                        break;
                    case 2:
                        $contract->status = 4;
                        $this->contractDocPopulate($contract);
                }
                break;
        }

        $contract->save();
        return redirect(url('contracts'))->with('data', 'Спасибо за одобрение.');
    }

    private function contractDocPopulate(Contract $contract)
    {
        $urlResources = resource_path();
        $url = URL::signedRoute('contractProve', ['id' => $contract->id]);
        $mageUrl = $urlResources . '\contracts\contractsQrCodes\qrcode-' . $contract->docN . '.png';
        $imageWord = array("path" => $mageUrl, "width" => 100, "height" => 100);
        QrCode::format('png')->size(500)->generate($url, $mageUrl);

        $templateProcessor = new \PhpOffice\PhpWord\TemplateProcessor($urlResources . '\contracts\tpl\contract.docx');
        $templateProcessor->setValue('contractNumber', $contract->docN);
        $templateProcessor->setValue('sellerBankName', $contract->s_bank_name);
        $templateProcessor->setValue('sellerBankAccount', $contract->s_bank_name);
        $templateProcessor->setValue('sellerBankCode', $contract->s_bank_name);
        $templateProcessor->setValue('buyerBankName', $contract->s_bank_name);
        $templateProcessor->setValue('buyerBankAccount', $contract->s_bank_name);
        $templateProcessor->setValue('buyerrBankCode', $contract->s_bank_name);
        $templateProcessor->setImageValue('image', $imageWord);
        $templateProcessor->saveAs($urlResources . '\contracts\ready\_' . $contract->docN . '.docx');
    }
}

resources/views/dashboard/products/create.blade.php
@extends('dashboard.layouts.app')

@section('title')
    Новый товар
@endsection

@section('content')

<div class="dashboard-headline">
    <h3>Новый товар</h3>

    <nav id="breadcrumbs" class="dark">
        <ul>
            <li>
                <a href="{{ url('dashboard') }}">
                    Профиль
                </a>
            </li>
            <li>
                <a href="{{ route('ownProducts.index') }}">
                    Мои товары
                </a>
            </li>
            <li>Новый товар</li>
        </ul>
    </nav>
</div>

{!! Form::open(['method' => 'POST','route' => 'ownProducts.store', 'onsubmit' => 'return validateForm()', 'files' => true]) !!}

    @include('dashboard.products.fields')

{!! Form::close() !!}

@endsection

resources/views/dashboard/products/edit.blade.php
@extends('dashboard.layouts.app')

@section('title')
    Новый товар
@endsection

@section('content')

<div class="dashboard-headline">
    <h3>{{ $product->title }}</h3>

    <nav id="breadcrumbs" class="dark">
        <ul>
            <li>
                <a href="{{ url('dashboard') }}">
                    Профиль
                </a>
            </li>
            <li>
                <a href="{{ route('ownProducts.index') }}">
                    Мои товары
                </a>
            </li>
            <li>Редактировать товар</li>
        </ul>
    </nav>
</div>

{!! Form::model($product, ['route' => ['ownProducts.update', $product->id], 'method' => 'patch', 'files' => true]) !!}

    @include('dashboard.products.fields')

{!! Form::close() !!}

@endsection

resources/views/dashboard/products/index.blade.php
@extends('dashboard.layouts.app')

@section('title')
    Own products
@endsection
@section('content')

    @if (count($errors) > 0)
        <div class="notification error closeable">
            @foreach ($errors->all() as $error)
                <p>{{ $error }}</p>
            @endforeach
            <a class="close" href="#"></a>
        </div>
    @endif

    <div class="dashboard-headline">
        <h3>Мои товары</h3>

        <!-- Breadcrumbs -->
        <nav id="breadcrumbs" class="dark">
            <ul>
                <li>
                    <a href="{{ route('ownProducts.create') }}">
                        Добавить товар&nbsp;<i class="icon-feather-file-plus"></i>
                    </a>
                </li>
            </ul>
        </nav>
    </div>

    <!-- Row -->
    <div class="row">

        <!-- Dashboard Box -->
        <div class="col-xl-12">
            <div class="dashboard-box margin-top-0">
                <div class="content">
                    <ul class="dashboard-box-list">
                        @foreach ($products as $product)
                            <li>
                                <!-- Job Listing -->
                                <div class="job-listing">

                                    <!-- Job Listing Details -->
                                    <div class="job-listing-details">

                                        <!-- Logo -->
                                        <a href="{{ LaravelLocalization::getLocalizedURL($locale, 'product/'.$product->slug) }}"
                                           class="job-listing-company-logo">
                                            {{ Html::image('uploads/product/admin_'.$product->featured_image) }}
                                        </a>

                                        <!-- Details -->
                                        <div class="job-listing-description">
                                            <h3 class="job-listing-title">
                                                <a href="{{ LaravelLocalization::getLocalizedURL($locale, 'product/'.$product->slug) }}">
                                                    {{ $product->title }}
                                                </a>
                                            </h3>

                                            <!-- Job Listing Footer -->
                                            <div class="job-listing-footer">
                                                <ul>
                                                    <li>
                                                <span class="dashboard-status-button {{ $product->statusTable->front_css }}">
                                                    {{ $product->statusTable->name }}
                                                </span>
                                                    </li>
                                                    <br>
                                                    <li>
                                                        <i class="icon-material-outline-date-range"></i>
                                                        &nbsp;Posted
                                                        on {{ Carbon\Carbon::parse($product->created_at)->format('d/m/Y') }}
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <!-- Buttons -->
                                <div class="buttons-to-right always-visible">
                                    <a href="#" class="button ripple-effect">
                                        {{ $product->categoryMain->title }}
                                        <i class="icon-material-outline-arrow-right"></i>
                                    </a>
                                    <a href="#" class="button ripple-effect">
                                        {{ $product->categoryChild->title }}
                                    </a>
                                    <a href="{{ route('ownProducts.edit',$product->id) }}"
                                       class="button gray ripple-effect ico" title="Изменить" data-tippy-placement="top">
                                        <i class="icon-feather-edit"></i>
                                    </a>

                                    @if ($product->status == 9 || $product->status == 4)
                                        <a href="{{ url('productRefresh/'. $product->id) }}"
                                           class="button gray ripple-effect"
                                           title="Активировать" data-tippy-placement="top">
                                            <i class="icon-material-outline-redo"></i>
                                        </a>
                                    @else
                                        <a href="#"
                                           onclick="document.getElementById('deActivate-{{$product->id}}').submit()"
                                           class="button gray ripple-effect ico" title="Деактивировать"
                                           data-tippy-placement="top">
                                            <i class="icon-feather-trash-2"></i>
                                        </a>
                                        <form action="{{ route('ownProducts.destroy', $product->id) }}" method="POST"
                                              id="deActivate-{{$product->id}}">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                        </form>
                                    @endif
                                </div>
                            </li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
        {{ $products->links() }}
    </div>
@endsection