routes/web.php
<?php

use App\Events\MessagePosted;
use App\Message;
use Illuminate\Support\Facades\Auth;

Route::group(
[
	'prefix' => LaravelLocalization::setLocale(),
	'middleware' => [ 'localize', 'localizationRedirect', 'activity' ]
],
function()
{
    Route::get('/', 'HomeController@index');
    Route::get('contractProve/{id}', ['as'=> 'contractProve', 'uses' => 'HomeController@contractProve']);
    Route::get('categories', 'HomeController@categoryPage');
    Route::get('profile', 'HomeController@profile');
	Route::get('profileEdit', 'HomeController@profileEdit');
    Route::get('api/getCities','HomeController@getCities');
    Route::get('api/getDistricts','HomeController@getDistricts');
    Route::post('registeration', 'HomeController@registeration');
    Auth::routes(['verify' => true]);

    Route::get('products', 'ProductFrontController@index');
    Route::get('product/{slug}', ['as'=> 'product.show', 'uses' => 'ProductFrontController@show']);
    Route::get('category/{id}', 'ProductFrontController@showByCategory');
    Route::post('price-request', 'ProductFrontController@priceRequest');
    Route::post('price-offer', 'ProductFrontController@priceOffer');

    Route::get('dashboard', 'Dashboard\DashboardController@index');
    Route::get('reserves', 'Dashboard\DashboardController@reserves');
    Route::get('contracts', 'Dashboard\ContractController@index');
    Route::get('contract/{id}', 'Dashboard\ContractController@view');
    Route::post('contractLoad', 'Dashboard\ContractController@contractLoad');
    Route::get('contractApprove/{id}', 'Dashboard\ContractController@approve');
    Route::get('notification/{id}', 'Dashboard\DashboardController@notification');
    Route::resource('ownProducts','Dashboard\ProductController');
    Route::get('productRefresh/{id}', 'Dashboard\ProductController@refresh');
    Route::resource('rkps', 'Dashboard\RkpController');

    Route::get('api/getChildCategories','Dashboard\ProductController@getChildCategories');
    Route::get('api/getUserSaldo','Dashboard\ProductController@getUserSaldo');
});

Route::group(['prefix' => 'backend','middleware' => ['role:admin', 'activity']], function() {

	Route::get('/', 'Admin\Backend');

    Route::resource('roles','Admin\RoleController');
    Route::resource('users','Admin\UserController');
    Route::resource('permissions','Admin\PermissionController');

    Route::resource('rkpsAdmin', 'Admin\RkpBackendController');
    Route::resource('payments', 'Admin\PaymentController');

    Route::resource('cities', 'Admin\CityController');
    Route::resource('districts', 'Admin\DistrictController');

    Route::resource('categories', 'Admin\CategoryController');
    Route::resource('childCategories', 'Admin\CategoryChildController');

    Route::resource('measures', 'Admin\MeasureController');
    Route::resource('currencies', 'Admin\CurrencyController');
    Route::resource('basises', 'Admin\BasisController');
    Route::resource('products', 'Admin\ProductController');

    Route::get('contracts', ['as' => 'contracts.index', 'uses' => 'Admin\ContractsController@index']);
    Route::get('contractStatuses', ['as' => 'contractStatuses.index', 'uses' => 'Admin\ContractStatusesController@index']);
    Route::post('docPayments', ['as' => 'docPayment.create','uses' => 'Admin\PaymentController@docPaymentCreate']);

    Route::resource('holidays', 'Admin\HolidaysController');
    Route::resource('statuses', 'Admin\StatusController');
    Route::get('params', ['as' => 'params.index', 'uses' => 'Admin\SystemParamsController@index']);
    Route::put('params', ['as' => 'params.update', 'uses' => 'Admin\SystemParamsController@update']);

    Route::get('api/getDistricts','Admin\UserController@getDistricts');
    Route::get('users/reset/{id}','Admin\UserController@reset');

});
Route::group(['prefix' => 'messages', 'middleware'=> ['activity']], function () {
    Route::get('/', ['as' => 'messages', 'uses' => 'Dashboard\MessagesController@index']);
    Route::get('/sent', ['as' => 'messages.sent', 'uses' => 'Dashboard\MessagesController@sent']);
    Route::get('create', ['as' => 'messages.create', 'uses' => 'Dashboard\MessagesController@create']);
    Route::post('/', ['as' => 'messages.store', 'uses' => 'Dashboard\MessagesController@store']);
    Route::get('{id}', ['as' => 'messages.show', 'uses' => 'Dashboard\MessagesController@show']);
    Route::put('{id}', ['as' => 'messages.update', 'uses' => 'Dashboard\MessagesController@update']);

});

app/Http/Controllers/Admin/CategoryChildController.php
<?php

namespace App\Http\Controllers\Admin;

use Flash;
use App\Models\Category;
use App\Models\ChildCategory;
use App\Http\Requests\CategoryRequest;
use App\Repositories\ChildCategoryRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryChildController  extends Controller
{
    private $categoryRepository;

    public function __construct(ChildCategoryRepository $categoryRepo)
    {
        $this->categoryRepository = $categoryRepo;
    }

    public function index(Request $request)
    {
        $categories = ChildCategory::whereTranslation('locale', 'ru')->paginate(10);

        return view('admin.categoryChild.index', compact(['categories']));
    }

    public function create()
    {
        $parentCategories = Category::whereTranslation('locale', 'ru')->get();
        $parentCategoriesArray = [];

        foreach($parentCategories as $parentCategory) {
            $parentCategoriesArray[$parentCategory->id] = $parentCategory->title;
        }

        return view('admin.categoryChild.create', compact(['parentCategoriesArray']));
    }

    public function store(Request $request)
    {
        $this->validate($request, ChildCategory::$rules);
        ChildCategory::create($request->all());
        Flash::success('Child Category saved successfully.');

        return redirect(route('childCategories.index'));
    }

    public function show($id){}

    public function edit($id)
    {
        $category = ChildCategory::find($id);

        if (empty($category)) {
            Flash::error('Category not found');

            return redirect(route('childCategories.index'));
        }

        $parentCategories = Category::whereTranslation('locale', 'ru')->get();
        $parentCategoriesArray = [];

        foreach($parentCategories as $parentCategory) {
            $parentCategoriesArray[$parentCategory->id] = $parentCategory->title;
        }

        return view('admin.categoryChild.edit', compact(['category', 'parentCategoriesArray']));
    }

    public function update(CategoryRequest $request, $id)
    {
        $category = ChildCategory::find($id);

        if (empty($category)) {
            Flash::error('Category not found');

            return redirect(route('childCategories.index'));
        }

        $category = $this->categoryRepository->update($request->all(), $id);

        Flash::success('Category updated successfully.');

        return redirect(route('childCategories.index'));
    }

    public function destroy($id)
    {
        $category = ChildCategory::find($id);

        if (empty($category)) {
            Flash::error('Category not found');

            return redirect(route('childCategories.index'));
        }

        $category->delete($id);

        Flash::success('Category deleted successfully.');

        return redirect(route('childCategories.index'));
    }
}

resources/views/admin/categoryChild/create.blade.php
<?php ?>
@extends('admin.layouts.app')

@section('content')
    <div class="">
        <div class="row">
                <div class="panel panel-default">
                    <div class="panel-heading">Create New Child Category</div>

                    <div class="panel-body">
                        <!-- Display Validation Errors -->
                        @if (count($errors) > 0)
                        <div class="alert alert-danger alert-dismissible fade in" role="alert"> 
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button> 
                            <strong>Whoops!</strong> There were some problems with your input.<br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                        @endif

                        {!! Form::open(['route' => 'childCategories.store']) !!}

                            @include('admin.categoryChild.fields')

                        {!! Form::close() !!}

                    </div>
                </div>
            </div>
        </div>
@endsection

resources/views/admin/categoryChild/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Edit child category
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($category, ['route' => ['childCategories.update', $category->id], 'method' => 'patch']) !!}

                        @include('admin.categoryChild.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/admin/categoryChild/fields.blade.php
<div class="nav-tabs-custom col-xs-12">

    <ul class="nav nav-tabs">
        <?php $key = 1;
        foreach( LaravelLocalization::getSupportedLocales() as $locale => $properties ): ?>
        <li class="{{ $key==1 ? 'active' : '' }}">
            <a href="#tab_{{ $key }}" data-toggle="tab">
                <span class="locale-title"><i class="fa fa-globe" aria-hidden="true"></i> {{ $properties['native'] }}</span>
            </a>
        </li>
        <?php $key++; endforeach; ?>
    </ul>

    <div class="tab-content">
        <?php $key = 1;
        foreach( LaravelLocalization::getSupportedLocales() as $locale => $properties ): ?>
        <div class="tab-pane {{ $key==1 ? 'active' : '' }}" id="tab_{{ $key }}">

            <div class="form-group col-sm-6">
                {!! Form::label($locale.'[title]', 'Заголовок:') !!}
                {{ Form::text(
                    $locale.'[title]',
                    isset($category) ? $category->translate($locale)->title : null,
                    ['class' => 'form-control'])
                }}
            </div>

            <div class="form-group col-sm-6">
                {!! Form::label($locale.'[slug]', 'URL:') !!}
                {{ Form::text(
                    $locale.'[slug]',
                    isset($category) ? $category->translate($locale)->slug : null,
                    ['class' => 'form-control',
                    'disabled' => isset($category) ? null : 'true'])
                }}
            </div>
        </div>  
        <?php $key++; endforeach; ?>
    </div>
    <div class="clearfix"></div>
    <div class="form-group col-sm-6">
        {!! Form::label(false, 'Иконка') !!}

        {{ Form::text('image',
            isset($category) ? $category->image : null,
            ['class' => 'form-control'])
        }}
    </div>
    <div class="form-group col-sm-6">
        {!! Form::label(false, 'Категория') !!}

        {!! Form::select('category_id', ['' => 'Select'] + $parentCategoriesArray, null, ['class' => 'form-control']) !!}
    </div>
    <div class="clearfix"></div>
    <!-- Submit Field -->
    <div class="form-group col-sm-12">
        {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
        <a href="{!! route('categories.index') !!}" class="btn btn-default">Cancel</a>
    </div>
</div>

resources/views/admin/categoryChild/index.blade.php
<?php ?>
@extends('admin.layouts.app')

@section('content')
<div class="panel panel-default">
    <div class="panel-heading">
        Child Categories Management 
        <a href="{{ route('childCategories.create') }}" class="btn btn-success">
            <i class="fa fa-btn fa-plus"></i> 
            &nbsp;New Child Category
        </a>
    </div>
    <div class="panel-body">
        @include('flash::message')
        <table class="table table-striped table-bordered table-condensed">
            <thead>
            <tr>
                <th>Name</th>
                <th>Category</th>
                <th></th>
            </tr>
            </thead>
            <tbody>

            @foreach ($categories as $key => $category)

                <tr class="categories-users">
                    <td>{{ $category->title }}</td>
                    <td>{{ $category->category->title }}</td>
                    <td>
                        <a class="btn btn-primary" href="{{ route('childCategories.edit',$category->id) }}"><i class="fa fa-btn fa-edit"></i> Edit</a>

                        <form action="{{ url('backend/childCategories/'.$category->id) }}" method="POST" style="display: inline-block">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}

                            <button type="submit" id="delete-task-{{ $category->id }}" class="btn btn-danger">
                                <i class="fa fa-btn fa-trash"></i> Delete
                            </button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
</div>
{{ $categories->links() }}
@endsection