routes/web.php
<?php

use App\Events\MessagePosted;
use App\Message;
use Illuminate\Support\Facades\Auth;

Route::group(
[
	'prefix' => LaravelLocalization::setLocale(),
	'middleware' => [ 'localize', 'localizationRedirect', 'activity' ]
],
function()
{
    Route::get('/', 'HomeController@index');
    Route::get('contractProve/{id}', ['as'=> 'contractProve', 'uses' => 'HomeController@contractProve']);
    Route::get('categories', 'HomeController@categoryPage');
    Route::get('profile', 'HomeController@profile');
	Route::get('profileEdit', 'HomeController@profileEdit');
    Route::get('api/getCities','HomeController@getCities');
    Route::get('api/getDistricts','HomeController@getDistricts');
    Route::post('registeration', 'HomeController@registeration');
    Auth::routes(['verify' => true]);

    Route::get('products', 'ProductFrontController@index');
    Route::get('product/{slug}', ['as'=> 'product.show', 'uses' => 'ProductFrontController@show']);
    Route::get('category/{id}', 'ProductFrontController@showByCategory');
    Route::post('price-request', 'ProductFrontController@priceRequest');
    Route::post('price-offer', 'ProductFrontController@priceOffer');

    Route::get('dashboard', 'Dashboard\DashboardController@index');
    Route::get('reserves', 'Dashboard\DashboardController@reserves');
    Route::get('contracts', 'Dashboard\ContractController@index');
    Route::get('contract/{id}', 'Dashboard\ContractController@view');
    Route::post('contractLoad', 'Dashboard\ContractController@contractLoad');
    Route::get('contractApprove/{id}', 'Dashboard\ContractController@approve');
    Route::get('notification/{id}', 'Dashboard\DashboardController@notification');
    Route::resource('ownProducts','Dashboard\ProductController');
    Route::get('productRefresh/{id}', 'Dashboard\ProductController@refresh');
    Route::resource('rkps', 'Dashboard\RkpController');

    Route::get('api/getChildCategories','Dashboard\ProductController@getChildCategories');
    Route::get('api/getUserSaldo','Dashboard\ProductController@getUserSaldo');
});

Route::group(['prefix' => 'backend','middleware' => ['role:admin', 'activity']], function() {

	Route::get('/', 'Admin\Backend');

    Route::resource('roles','Admin\RoleController');
    Route::resource('users','Admin\UserController');
    Route::resource('permissions','Admin\PermissionController');

    Route::resource('rkpsAdmin', 'Admin\RkpBackendController');
    Route::resource('payments', 'Admin\PaymentController');

    Route::resource('cities', 'Admin\CityController');
    Route::resource('districts', 'Admin\DistrictController');

    Route::resource('categories', 'Admin\CategoryController');
    Route::resource('childCategories', 'Admin\CategoryChildController');

    Route::resource('measures', 'Admin\MeasureController');
    Route::resource('currencies', 'Admin\CurrencyController');
    Route::resource('basises', 'Admin\BasisController');
    Route::resource('products', 'Admin\ProductController');

    Route::get('contracts', ['as' => 'contracts.index', 'uses' => 'Admin\ContractsController@index']);
    Route::get('contractStatuses', ['as' => 'contractStatuses.index', 'uses' => 'Admin\ContractStatusesController@index']);
    Route::post('docPayments', ['as' => 'docPayment.create','uses' => 'Admin\PaymentController@docPaymentCreate']);

    Route::resource('holidays', 'Admin\HolidaysController');
    Route::resource('statuses', 'Admin\StatusController');
    Route::get('params', ['as' => 'params.index', 'uses' => 'Admin\SystemParamsController@index']);
    Route::put('params', ['as' => 'params.update', 'uses' => 'Admin\SystemParamsController@update']);

    Route::get('api/getDistricts','Admin\UserController@getDistricts');
    Route::get('users/reset/{id}','Admin\UserController@reset');

});
Route::group(['prefix' => 'messages', 'middleware'=> ['activity']], function () {
    Route::get('/', ['as' => 'messages', 'uses' => 'Dashboard\MessagesController@index']);
    Route::get('/sent', ['as' => 'messages.sent', 'uses' => 'Dashboard\MessagesController@sent']);
    Route::get('create', ['as' => 'messages.create', 'uses' => 'Dashboard\MessagesController@create']);
    Route::post('/', ['as' => 'messages.store', 'uses' => 'Dashboard\MessagesController@store']);
    Route::get('{id}', ['as' => 'messages.show', 'uses' => 'Dashboard\MessagesController@show']);
    Route::put('{id}', ['as' => 'messages.update', 'uses' => 'Dashboard\MessagesController@update']);

});

app/Models/Basis.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

class Basis extends Model
{
    use \Dimsav\Translatable\Translatable;

    public $table = 'basis';

    public $translationModel = 'App\Models\BasisTranslation';

    public $translatedAttributes = [
        'title',
        'slug',
    ];

    public $timestamps = false;

    protected $fillable = ['icon', 'code'];

    public static $rules = [
        'ru.title' => 'required|string|min:1|max:255',
        'uz.title' => 'required|string|min:1|max:255',
        'en.title' => 'required|string|min:1|max:255',
        'code' => 'required|string|min:1|max:20',
    ];

    protected static function boot() {
        parent::boot();

        static::deleting(function($category) {
            $category->deleteTranslations();
        });
    }
}

app/Http/Controllers/Admin/BasisController.php
<?php

namespace App\Http\Controllers\Admin;

use Prettus\Repository\Criteria\RequestCriteria;
use App\Http\Controllers\AppBaseController;
use App\Repositories\BasisRepository;
use App\Http\Requests\BasisRequest;
use Illuminate\Http\Request;
use App\Models\Basis;
use Response;
use Flash;

class BasisController extends AppBaseController
{
    private $repository;

    public function __construct(BasisRepository $baseRepo)
    {
        $this->repository = $baseRepo;
    }

    public function index(Request $request)
    {
        $basises = Basis::whereTranslation('locale', 'ru')->paginate(10);

        return view('admin.basis.index')->with('basises', $basises);
    }

    public function create()
    {
        return view('admin.basis.create');
    }

    public function store(BasisRequest $request)
    {

        $input = $request->all();

        $this->repository->create($input);

        Flash::success('Basis saved successfully.');

        return redirect(route('basises.index'));
    }

    public function edit($id)
    {
        $basis = $this->repository->findWithoutFail($id);

        if (empty($basis)) {
            Flash::error('Basis not found');
            return redirect(route('basises.index'));
        }

        return view('admin.basis.edit')->with('basis', $basis);
    }

    public function update($id, BasisRequest $request)
    {
        $basis = $this->repository->findWithoutFail($id);

        if (empty($basis)) {
            Flash::error('Basis not found');
            return redirect(route('basises.index'));
        }

        $basis = $this->repository->update($request->all(), $id);

        Flash::success('Basis updated successfully.');

        return redirect(route('basises.index'));
    }

    public function destroy($id)
    {
        $basis = $this->repository->findWithoutFail($id);

        if (empty($basis)) {
            Flash::error('Basis not found');
            return redirect(route('basises.index'));
        }

        $this->repository->delete($id);

        Flash::success('Basis deleted successfully.');

        return redirect(route('basises.index'));
    }
}

resources/views/admin/basis/create.blade.php
<?php ?>
@extends('admin.layouts.app')

@section('content')
    <div class="">
        <div class="row">
                <div class="panel panel-default">
                    <div class="panel-heading">Create New Currency</div>

                    <div class="panel-body">
                        @if (count($errors) > 0)
                            <div class="alert alert-danger alert-dismissible fade in" role="alert"> 
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">×</span>
                                </button> 
                                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        {!! Form::open(['route' => 'basises.store']) !!}

                            @include('admin.basis.fields')

                        {!! Form::close() !!}

                    </div>
                </div>
            </div>
        </div>
@endsection

resources/views/admin/basis/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Edit basis
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($basis, ['route' => ['basises.update', $basis->id], 'method' => 'patch']) !!}

                        @include('admin.basis.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/admin/basis/fields.blade.php
<div class="nav-tabs-custom col-xs-12">

    <ul class="nav nav-tabs">
        <?php $key = 1;
        foreach( LaravelLocalization::getSupportedLocales() as $locale => $properties ): ?>
        <li class="{{ $key==1 ? 'active' : '' }}">
            <a href="#tab_{{ $key }}" data-toggle="tab">
                <span class="locale-title"><i class="fa fa-globe" aria-hidden="true"></i> {{ $properties['native'] }}</span>
            </a>
        </li>
        <?php $key++; endforeach; ?>
    </ul>

    <div class="tab-content">
        <?php $key = 1;
        foreach( LaravelLocalization::getSupportedLocales() as $locale => $properties ): ?>
        <div class="tab-pane {{ $key==1 ? 'active' : '' }}" id="tab_{{ $key }}">

            <div class="form-group col-sm-6">
                {!! Form::label($locale.'[title]', 'Заголовок:') !!}
                {{ Form::text(
                    $locale.'[title]',
                    isset($basis) ? $basis->translate($locale)->title : null,
                    ['class' => 'form-control'])
                }}
            </div>

            <div class="form-group col-sm-6">
                {!! Form::label($locale.'[slug]', 'URL:') !!}
                {{ Form::text(
                    $locale.'[slug]',
                    isset($basis) ? $basis->translate($locale)->slug : null,
                    ['class' => 'form-control',
                    'disabled' => isset($basis) ? null : 'true'])
                }}
            </div>
        </div>  
        <?php $key++; endforeach; ?>
    </div>

    <div class="form-group col-sm-6">
        {!! Form::label('code', 'Код:') !!}
        {{ Form::text(
            'code',
            isset($basis) ? $basis->code : null,
            ['class' => 'form-control'])
        }}
    </div>

    <!-- Submit Field -->
    <div class="form-group col-sm-12">
        {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
        <a href="{!! route('basises.index') !!}" class="btn btn-default">Cancel</a>
    </div>
</div>

resources/views/admin/basis/index.blade.php
<?php ?>
@extends('admin.layouts.app')

@section('content')
    <div class="container">
        <div class="row">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Basis Management&nbsp;
                        <a href="{{ route('basises.create') }}" class="btn btn-success">
                            <i class="fa fa-btn fa-plus"></i> 
                            &nbsp;New Basis
                        </a>
                    </div>
                    <div class="panel-body">
                        @include('flash::message')
                        <table class="table table-striped table-bordered table-condensed">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>

                            @foreach ($basises as $key => $value)

                                <tr class="basises-users">
                                    <td>{{ $value->title }}</td>
                                    <td>
                                        <a class="btn btn-primary" href="{{ route('basises.edit',$value->id) }}"><i class="fa fa-btn fa-edit"></i> Edit</a>

                                        <form action="{{ url('backend/basises/'.$value->id) }}" method="POST" style="display: inline-block">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}

                                            <button type="submit" id="delete-task-{{ $value->id }}" class="btn btn-danger">
                                                <i class="fa fa-btn fa-trash"></i> Delete
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                {{ $basises->links() }}
            </div>
        </div>
@endsection